name: Automated tests for Rostelecom

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Выберите тест
        required: true
        default: test_without_real_auth
        type: choice
        options:
          - test_without_real_auth
          - test_all
      phone:
        description: Телефон
        required: false
        type: 'string'
      email:
        description: Email
        required: false
        type: 'string'
      login:
        description: Логин
        required: false
        type: 'string'
      ls:
        description: Лицевой счет
        required: false
        type: 'string'
      password:
        description: Пароль
        required: false
        type: 'string'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run:  pip install -r requirements.txt

#   Set environment variable from SECRETS
      - name: Set environment variable
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PHONE: ${{ secrets.PHONE }}
          LS: ${{ secrets.LS }}
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "EMAIL=${{ secrets.EMAIL }}" >> $GITHUB_ENV
          echo "PHONE=${{ secrets.PHONE }}" >> $GITHUB_ENV
          echo "LS=${{ secrets.LS }}" >> $GITHUB_ENV
          echo "LOGIN=${{ secrets.LOGIN }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV

#   Overwrite env variable if exist inputs
      - name: Set input Email
        run: echo "EMAIL=${{ inputs.email }}" >> $GITHUB_ENV
        if: ${{ inputs.email }}
      - name: Set input Phone
        run: echo "PHONE=${{ inputs.phone }}" >> $GITHUB_ENV
        if: ${{ inputs.phone }}
      - name: Set input LS
        run: echo "LS=${{ inputs.ls }}" >> $GITHUB_ENV
        if: ${{ inputs.ls }}
      - name: Set input Login
        run: echo "LOGIN=${{ inputs.login }}" >> $GITHUB_ENV
        if: ${{ inputs.login }}
      - name: Set input Password
        run: echo "PASSWORD=${{ inputs.password }}" >> $GITHUB_ENV
        if: ${{ inputs.password }}

#   Run tests
      - name: Run tests exclude real auth data
        if: "github.event.inputs.deployment_target == 'test_without_real_auth'"
        run: python -m pytest -m "not real_auth" --alluredir allure-result
      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'test_all'"
        run: python -m pytest --alluredir allure-result

#   Get allure history
      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

#   Build allure report
      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-result
          allure_history: allure_history
          keep_reports: 20

#   Deploy allure report
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure_history
