name: Automated tests for Rostelecom

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Выберите тест
        required: true
        default: test_auth_page
        type: choice
        options:
          - test_auth_page
          - test_admin
      email:
        description: Email
        required: false
        type: 'string'
      phone:
        description: Телефон
        required: false
        type: 'string'
      uid:
        description: Лицевой счет
        required: false
        type: 'string'
      password:
        description: Пароль
        required: false
        type: 'string'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run:  pip install -r requirements.txt
      - name: Set environment variable
        run: |
          echo "EMAIL=${{ github.event.inputs.email }}" >> $GITHUB_ENV
          echo "PHONE=${{ github.event.inputs.phone }}" >> $GITHUB_ENV
          echo "UID=${{ github.event.inputs.uid }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ github.event.inputs.password }}" >> $GITHUB_ENV
      - name: Run tests
        if: "github.event.inputs.deployment_target == 'test_auth_page'"
        run: pytest


