name: Automated tests for Rostelecom

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Выберите тест
        required: true
        default: test_auth_page
        type: choice
        options:
          - test_auth_page
          - test_admin
      phone:
        description: Телефон
        required: false
        type: 'string'
      email:
        description: Email
        required: false
        type: 'string'
      login:
        description: Логин
        required: false
        type: 'string'
      ls:
        description: Лицевой счет
        required: false
        type: 'string'
      password:
        description: Пароль
        required: false
        type: 'string'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run:  pip install -r requirements.txt
      - name: Set environment variable
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PHONE: ${{ secrets.PHONE }}
          LS: ${{ secrets.LS }}
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "EMAIL=${{ secrets.EMAIL }}" >> $GITHUB_ENV
          echo "PHONE=${{ secrets.PHONE }}" >> $GITHUB_ENV
          echo "LS=${{ secrets.LS }}" >> $GITHUB_ENV
          echo "LOGIN=${{ secrets.LOGIN }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV
      - name: Set input Email
        run: echo "EMAIL=${{ inputs.email }}" >> $GITHUB_ENV
        if: ${{ inputs.email }}
      - name: Set input Phone
        run: echo "PHONE=${{ inputs.phone }}" >> $GITHUB_ENV
        if: ${{ inputs.phone }}
      - name: Set input LS
        run: echo "LS=${{ inputs.ls }}" >> $GITHUB_ENV
        if: ${{ inputs.ls }}
      - name: Set input Login
        run: echo "LOGIN=${{ inputs.login }}" >> $GITHUB_ENV
        if: ${{ inputs.login }}
      - name: Set input Password
        run: echo "PASSWORD=${{ inputs.password }}" >> $GITHUB_ENV
        if: ${{ inputs.password }}
      - name: Run tests
        if: "github.event.inputs.deployment_target == 'test_auth_page'"
        run: pytest
#        run: python -m pytest --alluredir allure-result
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          # gh_pages: gh-pages
          # allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

